-- Hacer campos opcionales en el modelo Informe
ALTER TABLE "Informe" ALTER COLUMN "equipo" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "noOrden" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "nSerie" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "cliente" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "sitio" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "tipoEquipo" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "tempAmbiente" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "versionFirmware" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "versionWebServer" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "snmpV1" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "snmpV2" DROP NOT NULL;
ALTER TABLE "Informe" ALTER COLUMN "equipoApto" SET DEFAULT false;
