export interface UcaItemDef {
  numero: string;
  descripcion: string;
}

export const UCA_ITEMS: UcaItemDef[] = [
  { numero: "1", descripcion: "Configuración UCA vía display, Web Server y gestión de Jumper" },
  { numero: "2", descripcion: "Credenciales de autentificación" },
  { numero: "3", descripcion: "Comprobación de todas las Pantallas de Configuración y Lectura de estados" },
  { numero: "4", descripcion: "Sustituir UCA sin producir Corte de la Emisión de FM" },
  { numero: "5", descripcion: "Comprobación Orden de Reset a Tx Individual" },
  { numero: "6", descripcion: "Comprobación Orden de Reset a todos los Tx" },
  { numero: "8", descripcion: "Comprobación señalización ON/OFF de todos los Tx" },
  { numero: "9", descripcion: "Comprobación Funcionamiento si Traba Sistema Radiante abierta" },
  { numero: "10", descripcion: "Comprobación Funcionamiento si Traba Carga Radiante abierta" },
  { numero: "11", descripcion: "Comprobación de Función Inicializar UCA" },
  { numero: "12", descripcion: "Comprobación de función Txs ON/Txs OFF" },
  { numero: "13", descripcion: "Comprobación de TxPn ON/OFF" },
  { numero: "14", descripcion: "Comprobación de TxR ON/OFF" },
  { numero: "15", descripcion: "Comprobación de la señalización de alarmas en la UCA" },
  { numero: "15.1", descripcion: "Alarma General Txn o TxR" },
  { numero: "15.2", descripcion: "Fallo RF Txn o TxR" },
  { numero: "15.3", descripcion: "Presencia/Ausencia de Red (AC) Txn o TxR" },
  { numero: "15.4", descripcion: "Señalización TxPn o TxR Local/Remoto" },
  { numero: "15.5", descripcion: "Fallo Matriz de Audio" },
  { numero: "15.6", descripcion: "Alarma de Motor Cxn" },
  { numero: "15.7", descripcion: "Descargar Log de Eventos" },
  { numero: "16", descripcion: "Comprobación de la Conmutación Manual de todos los TxP y TxR" },
  { numero: "16.1", descripcion: "TxP1 a TxPn a Carga" },
  { numero: "16.2", descripcion: "TxP1 a TxPn a Antena" },
  { numero: "16.3", descripcion: "TxR a Ax y TxR a Carga" },
  { numero: "16.4", descripcion: "Estado Inicial UCA" },
  { numero: "16.5", descripcion: "Tx's en Antena ON" },
  { numero: "16.6", descripcion: "Tx's OFF" },
  { numero: "16.7", descripcion: "TxPn ON/OFF" },
  { numero: "16.8", descripcion: "TxR ON/OFF" },
  { numero: "17", descripcion: "Comprobación de la Conmutación Automática de todos los TxP y TxR" },
  { numero: "17.1", descripcion: "Conmutación TxP1 a TxPn a Carga" },
  { numero: "17.2", descripcion: "Conmutación TxP1 a TxPn a Antena" },
  { numero: "17.3", descripcion: "Conmutación TxR a Ax y TxR a Carga" },
  { numero: "17.4", descripcion: "Conmutaciones con Prioridad" },
  { numero: "17.5", descripcion: "Conmutaciones con Prioridad Cero" },
  { numero: "17.6", descripcion: "Conmutación si Fallo TxR en Ax y en ON" },
];
