import type { MedidaColumn, MedidaRow } from "../types/verificacion";

export const DEFAULT_MEDIDAS: MedidaRow[] = [
  {
    frecMhz: 88,
    potW: null,
    vpaV: null,
    ipa1: null,
    ipa2: null,
    ipa3: null,
    tOut: null,
    tCase: null,
    tPwS: null,
    eff: null,
    if1: null,
    if2: null,
    if3: null,
  },
  {
    frecMhz: 98,
    potW: null,
    vpaV: null,
    ipa1: null,
    ipa2: null,
    ipa3: null,
    tOut: null,
    tCase: null,
    tPwS: null,
    eff: null,
    if1: null,
    if2: null,
    if3: null,
  },
  {
    frecMhz: 108,
    potW: null,
    vpaV: null,
    ipa1: null,
    ipa2: null,
    ipa3: null,
    tOut: null,
    tCase: null,
    tPwS: null,
    eff: null,
    if1: null,
    if2: null,
    if3: null,
  },
  {
    frecMhz: null,
    potW: null,
    vpaV: null,
    ipa1: null,
    ipa2: null,
    ipa3: null,
    tOut: null,
    tCase: null,
    tPwS: null,
    eff: null,
    if1: null,
    if2: null,
    if3: null,
  },
];

export const MEDIDA_COLUMNS = [
  { key: "frecMhz", label: "Frec. (MHz)", locked: true },
  { key: "potW", label: "Pot (W)", locked: false },
  { key: "vpaV", label: "Vpa (V)", locked: false },
  { key: "ipa1", label: "Ipa1 (A)", locked: false },
  { key: "ipa2", label: "Ipa2 (A)", locked: false },
  { key: "ipa3", label: "Ipa3 (A)", locked: false },
  { key: "tOut", label: "TOut (ºC)", locked: false },
  { key: "tCase", label: "TCase (ºC)", locked: false },
  { key: "tPwS", label: "TPwS (ºC)", locked: false },
  { key: "eff", label: "Eff (%)", locked: false },
  { key: "if1", label: "IF1 (A)", locked: false },
  { key: "if2", label: "IF2 (A)", locked: false },
  { key: "if3", label: "IF3 (A)", locked: false },
] as const satisfies ReadonlyArray<MedidaColumn>;

export const LOCKED_ROW_COUNT = 3;
